version: "3.0"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  php:
    image: php:8.0-mysql-xdebug-3
    command: php console/stock-tester.php
    volumes:
      - ./php/app:/app
    working_dir: /app
    depends_on:
      - mysql

